name: Feature Request
description: Suggest an idea for OMNIX AI
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for OMNIX AI!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: dropdown
    id: user-type
    attributes:
      label: Who would benefit from this feature?
      multiple: true
      options:
        - Managers
        - Customers
        - Administrators
        - Developers
        - All users
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current workflow)
        - High (Would significantly improve experience)
        - Medium (Nice to have)
        - Low (Small improvement)
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Dashboard & Analytics
        - Inventory Management
        - Customer Experience
        - AI & Recommendations
        - Authentication & Security
        - Performance & Optimization
        - Mobile Experience
        - Accessibility
        - Integration
        - Other
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false
      
  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, provide mockups, wireframes, or examples of similar features from other applications.
      
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have technical knowledge, describe how you think this could be implemented.
      placeholder: This could be implemented by...
    validations:
      required: false
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define what "done" looks like for this feature:
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
      placeholder: |
        - [ ] Feature is accessible via main navigation
        - [ ] Feature works on mobile devices
        - [ ] Feature includes proper error handling
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/omnix-ai/react/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true